// Renders the app icon PNGs from the SVGs in public/icons. Run: node scripts/icons.cjs <path-to-playwright>
// The SVG artwork (Cat's Eye logo) is generated by branding/gen.cjs in the project files.
const { chromium } = require(process.argv[2] || 'playwright')
const fs = require('fs')
const path = require('path')
const dir = path.join(__dirname, '..', 'public', 'icons')
;(async () => {
  const b = await chromium.launch()
  const p = await b.newPage()
  for (const ed of ['player', 'gm']) {
    const jobs = [[`${ed}.svg`, [[512, ''], [192, ''], [180, '']]], [`${ed}-maskable.svg`, [[512, '-maskable'], [192, '-maskable']]]]
    for (const [file, sizes] of jobs) {
      const svg = fs.readFileSync(path.join(dir, file), 'utf8')
      for (const [size, suffix] of sizes) {
        await p.setViewportSize({ width: size, height: size })
        await p.setContent(`<html><body style="margin:0">${svg.replace('<svg ', `<svg width="${size}" height="${size}" `)}</body></html>`)
        await p.screenshot({ path: path.join(dir, `${ed}${suffix}-${size}.png`) })
      }
    }
  }
  await b.close()
})()
